ignore  = ".gitignore"
exclude = "vendor/**/*"

[[commands]]

  [[commands.golangci-lint]]
  type    = "lint"
  include = "**/*.go"
  cmd     = ["golangci-lint", "run"]
  args    = ["--config", "$CONFIG_DIR/.golangci-lint.yml"]
  on_dir  = true
  ok_exit_codes = 0
